### ISSUE TITLE
Flasher blocked by Microsoft Defender

### ISSUE THREAD

**Issue by johansundstrom** [Jason2866/ESP_Flasher#1]
When downloading...

- ESP-Flasher-Windows-x86.exe
- ESP-Flasher-Windows-x64.exe

... from https://github.com/Jason2866/ESP_Flasher/releases, they are immidiately blocked by Microsoft. According to Microsoft Defender Antivirus, <a href="https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Program%3aWin32%2fWacapew.C!ml&threatid=265744">Win32/Wacapew.C!ml</a> is found. Recommendations given is to remove this file.

**Comment by Jason2866** [comment]
It is a known false alarm from pyinstaller. See https://stackoverflow.com/questions/54733909/windows-defender-alert-users-from-my-pyinstaller-exe
