### ISSUE TITLE
There is a solution to the missing DLL for Windows 7 32-bit 

### ISSUE THREAD

**Issue by Sum-Guy** [Jason2866/ESP_Flasher#15]
https://github.com/nalexandru/api-ms-win-core-path-HACK/releases/tag/0.3.1

Place a copy of the file api-ms-win-core-path-l1-1-0.dll (x86) in /windows/system32.  I have verified that ESP-Flasher2-Windows-x86.exe does now run correctly without error messages.

**Comment by Jason2866** [comment]
Thx, for the info. Since the source of the file and the license status is unknown
there will no build from my side for a x86 version.

**Comment by Jason2866** [comment]
Building with Python 3.7 results in a working build
