### ISSUE TITLE
MS Security Essentials finds Trojan:Win32/Zpevdo.B in ESP-Flasher-Windows-x86.exe

### ISSUE THREAD

**Issue by AuZ-ASD** [Jason2866/ESP_Flasher#2]
Hi,

just downloaded ESP-Flasher-Windows-x86.exe to flash my ESP cam but i cant as MS Security Essentials blocks and removes because it finds some Trojan:Win32/Zpevdo.B in the file

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fZpevdo.B&threatid=2147729093&enterprise=0

**Comment by Jason2866** [comment]
See #1

**Comment by almostlunatic** [comment]
OK, thanks a lot. Unfortunately _ cannot disable the corporate aantivirus program Bitdefender, so I jhave to find another way tu use it.

**Comment by Jason2866** [comment]
Do you have a running Python installed on your PC? Than you can install via pip as described inn the readme

**Comment by almostlunatic** [comment]
Nope, but I can do it, thanks!
