### ISSUE TITLE
Using alternative partition files

### ISSUE THREAD

**Issue by srg74** [Jason2866/ESP_Flasher#20]
I'm came from WLED firmware project. We using different partitions for our firmware. I would like to ask if it possible to use with your ESP flasher different partitions? If so how I can do it? I would like to inform you that I'm not a professional developer but I'm helping for WLED project to build bin files and wish to help with proper ESP flashing tool. Please help us.

**Comment by Jason2866** [comment]
You can fork my repo and replace the partitions bin in the root folder.

**Comment by srg74** [comment]
Thank you so much for your response. I already figure out path.
