### ISSUE TITLE
Won't start on Ubuntu 22.10

### ISSUE THREAD

**Issue by KlausHans** [Jason2866/ESP_Flasher#26]
Hello, unfortunately the Appimage won't start on Ubuntu 22.10. The terminal output is
```
(ESP-Flasher:23177): GLib-GIO-ERROR **: 16:20:19.396: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
Trace/Breakpoint ausgelöst (Speicherabzug geschrieben)
```

Can this be fixed? From what i googled, this has something to do with Wayland.

**Comment by Jason2866** [comment]
Currently no solution, since Github Actions has no runners supporting Ubuntu 22.10

**Comment by Jason2866** [comment]
Closing since Ubuntu 22.10 is out of support.
