### ISSUE TITLE
Cannot flash tasmota32.bin v13.2.0

### ISSUE THREAD

**Issue by felipeapp** [Jason2866/ESP_Flasher#27]
The esp32 keeps rebooting after flashing this binary (v13.2.0):
https://ota.tasmota.com/tasmota32/release/tasmota32.bin

But it worked with v12.5.0 binary:
https://ota.tasmota.com/tasmota32/release-12.5.0/tasmota32.bin

ESP Flasher is very good, any chance to keep it working with tasmota v13?

**Comment by Jason2866** [comment]
Can not reproduce. 
<img width="1117" alt="Bildschirmfoto 2023-11-01 um 17 50 08" src="https://github.com/Jason2866/ESP_Flasher/assets/24528715/05ec12fe-814b-4a72-8beb-291af44e97f0">

**Comment by Jason2866** [comment]
Ahh, wait. When using the version from the OTA Server it bootloops. Will investigate if this can be solved

**Comment by Jason2866** [comment]
If i find some spare time i will do a new version which supports the Tasmota safeboot scheme.

**Comment by felipeapp** [comment]
> After digging a bit more. The bootloader is still compatible. The answer is plain simple. Most actual Tasmota32 firmwares are too big to fit in the classic two OTA partition scheme (which is still used with ESP Flasher).
> For flashing this bigger firmwares the Tasmota safeboot Partition scheme is needed which ESP Flasher does NOT support.
> For flashing this bigger firmwares use Tasmota Web Installer https://tasmota.github.io/install/

Yes, the web installer works. However, use ESP Flasher to directly flash my custom tasmota firmwares would be great.

Thank you for your time, I'm going to wait for news.

**Comment by Jason2866** [comment]
You can try the version from the branch `safeboot`. Tested with an ESP32 and it did work.

**Comment by felipeapp** [comment]
> You can try the version from the branch `safeboot`. Tested with an ESP32 and it did work.

Great, this version works, thank you!

**Comment by Jason2866** [comment]
Don't be surprised when it breaks in between. It is not final... Will do a release on PyPi when it's done.

**Comment by Jason2866** [comment]
Prebuilt binaries in release section and available from PyPi

**Comment by felipeapp** [comment]
> Prebuilt binaries in release section and available from PyPi

Great! Everything is woking.
