### ISSUE TITLE
ESP-Flasher.exe is full of viruses

### ISSUE THREAD

**Issue by almostlunatic** [Jason2866/ESP_Flasher#34]
https://www.virustotal.com/gui/file/5401efd257572d78a62c719a95ebae69d0eb9ad4eacceb58c8ee8c014fa577db

Shame on you!

**Comment by Jason2866** [comment]
False Alert. See #1 #2  Search for Pyinstaller false Virus alert.
Relevant one https://github.com/pyinstaller/pyinstaller/issues/6754#issuecomment-1100821249
Won't buy a Windows certificate, i don't use Windows.
