### ISSUE TITLE
Pre-compiled ESP-Flasher.exe is flagging as a virus

### ISSUE THREAD

**Issue by Nathanlclark** [Jason2866/ESP_Flasher#35]
I already deleted the files but when I just downloaded the latest ESP-Flasher.exe it wouldn't allow the download with Chrome and when I tried with Firefox it let me know there was a virus in the program.

**Comment by Jason2866** [comment]
This are known false Virus alerts. The are caused from the used Pyinstaller to build the exe.
Nothing I can do anything. Just search for false Virus alerts with Pyinstaller with your favorite search engine. See #1

**Comment by Nathanlclark** [comment]
Thanks Jason,

Sorry for the noise.
