### ISSUE TITLE
404 when running

### ISSUE THREAD

**Issue by DeflateAwning** [Jason2866/ESP_Flasher#37]
Trying to install the Tasmota firmware. Got a 404 error within the log output of this program:

```
...
 - Flash Size: 4MB
Unexpected error: Error while retrieving firmware file 'https://raw.githubusercontent.com/Jason2866/ESP_Flasher/factory/bootloader/esp32/bin/bootloader_dout_40m.elf': 404 Client Error: Not Found for url: https://raw.githubusercontent.com/Jason2866/ESP_Flasher/factory/bootloader/esp32/bin/bootloader_dout_40m.elf

```

### Details
* Windows 10
* Installed via pip

**Comment by Jason2866** [comment]
Which Tasmota Firmware? Downloaded from? Please provide a link.

**Comment by DeflateAwning** [comment]
On mobile, but from here: https://ota.tasmota.com/tasmota/release/

It's this one: https://ota.tasmota.com/tasmota/release/tasmota-4M.bin

And also this one: https://ota.tasmota.com/tasmota/release/tasmota.bin

Flashing onto a board with 4M of flash memory

**Comment by Jason2866** [comment]
Ahh, an esp8266 firmware. That's a bug. For esp8266 no additional files are needed.

**Comment by DeflateAwning** [comment]
> Ahh, an esp8266 firmware. That's a bug. For esp8266 no additional files are needed.

Well it (Tasmota) supports both ESP8266 and the ESP32. I was flashing onto an ESP32

**Comment by Jason2866** [comment]
tasmota-4m is for esp8266! You can't use this firmware for ESP32.
For esp32 you have to use the Tasmota versions with "32" in the name.
Anyways it is a bug, for esp8266 no additional files are needed.
It is fixed now. Install latest version from PyPi
