### ISSUE TITLE
Windows 11: Windows Defender quarantines 2.2.3 exe for Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by Ares3D** [Jason2866/ESP_Flasher#38]
I cannot download the ESP_Flasher exe v2,2,3. No matter the browser, it is immediately quarantined by Windows Defender.

**Comment by Jason2866** [comment]
False Virus alert. Sorry can't change this. See #1

**Comment by Jason2866** [comment]
You can install the native Python version from PyPi
