### ISSUE TITLE
Current version .exe flagged as malware by Firefox

### ISSUE THREAD

**Issue by AlexC176** [Jason2866/ESP_Flasher#39]
Firefox 121.0.1 flags the current Windows.exe build as malware. 
Applies to all .exe versions back in time.
Virustotal.com analysis -

![image](https://github.com/Jason2866/ESP_Flasher/assets/62524745/fa2ebaed-115e-4067-a7ca-b217f9f0d61c)

**Comment by Jason2866** [comment]
See #1
