### ISSUE TITLE
Google Chrome blocks the download (virus)

### ISSUE THREAD

**Issue by ottelo9** [Jason2866/ESP_Flasher#46]
(German)
![image](https://github.com/Jason2866/ESP_Flasher/assets/33122175/808cab1f-9b43-4d60-aa6c-ade5e663916d)

Seems to be serious?https://www.virustotal.com/gui/file/c0cdec2fc219d78d915e929c7d38f5942dbb43ae020078a28064ba839459e6e8

Older version of .exe
https://www.virustotal.com/gui/file/ba140cd0ba1b70af907ed15247de60aa1ec6989ebc2c01d843983c0f9ba7140a

**Comment by Jason2866** [comment]
Known false alert. See other closed issues.

**Comment by Jason2866** [comment]
The APPs are build with GH Actions. With fresh initial build environments.

**Comment by ottelo9** [comment]
@Jason2866 
Maybe it would be a good idea to put this info on the main page as a big note.

**Comment by Jason2866** [comment]
Thx, added a note.
