### ISSUE TITLE
Unexpected error: Error while retrieving firmware file

### ISSUE THREAD

**Issue by spiri439** [Jason2866/ESP_Flasher#51]
Hello,

Can you please reupload this file https://raw.githubusercontent.com/Jason2866/ESP_Flasher/factory/bootloader/esp32/bin/bootloader_dout_40m.elf

Thank you,

**Comment by Jason2866** [comment]
No, since Tasmota setup does not use.

**Comment by CaptClaude** [comment]
> Hello,
> 
> Can you please reupload this file https://raw.githubusercontent.com/Jason2866/ESP_Flasher/factory/bootloader/esp32/bin/bootloader_dout_40m.elf
> 
> Thank you,

Make sure you are using the correct firmware for your chip. I was about to open another issue with the same error when I realized I was not uploading the correct firmware.  I have an ESP32-S3 and tasmota32s3.bin worked perfectly.
